import re

class Eliza:
    history = []
    backup = []
    replies = {
        "none": (   "I'm not sure I understand you fully.",
                    "Please go on.",
                    "What do you mean?",
                    "What does that suggest to you?",
                    "Do you feel strongly about discussing such things?",
                    "Why do you say that?"),
        "bye": (    "Thank you for the chat.",
                    "Good-bye."),
        "sorry": (  "Please don't apologise.",
                    "Apologies are not necessary.",
                    "I've told you that apologies are not required."),
        "i_remember_xyz":("Do you often think of {}?",
                    "Does thinking of {} bring anything else to mind?",
                    "What else do you recollect?",
                    "Why do you recollect {} just now?",
                    "What in the present situation reminds you of {}?",
                    "What is the connection between me and {}?"),
        "do_you_remember_xyz":("Did you think I would forget {}?",
                    "Why do you think I should recall {} now?",
                    "What about {}?",
                    "You mentioned {}?"),
        "if_xyz":(      "Do you think its likely that {}?",
                    "Do you wish that {}?",
                    "What do you know about {}?",
                    "Really, if {}?"),
        "i_dreamed_xyz":("Really, {}?",
                    "Have you ever fantasized {} while you were awake?",
                    "Have you ever dreamed {} before?"),
        "dream":(   "What does that dream suggest to you?",
                    "Do you dream often?",
                    "What persons appear in your dreams?",
                    "Do you believe that dreams have something to do with your problems?"),
        "perhaps":( "You don't seem quite certain.",
                    "Why the uncertain tone?",
                    "Can't you be more positive?",
                    "You aren't sure?",
                    "Don't you know?"),
        "name":(    "I am not interested in names.",
                    "I've told you before, I don't care about names -- please continue."),
        "hello":(   "How do you do.  Please state your problem.",
                    "Hi.  What seems to be your problem?"),
        "computer":("Do computers worry you?",
                    "Why do you mention computers?",
                    "What do you think machines have to do with your problem?",
                    "Don't you think computers can help people?",
                    "What about machines worrys you?",
                    "What do you think about machines?"),
        "am_i_xyz":(    "Do you believe you are {}?",
                    "Would you want to be {}?",
                    "Do you wish I would tell you you are {}?",
                    "What would it mean if you were {}?"),
        "am":(      "Why do you say 'am'?",
                    "I don't understand that."),
        "are_you_xyz":("Why are you interested in whether I am {} or not?",
                    "Would you prefer if I weren't {}?",
                    "Perhaps I am {} in your fantasies.",
                    "Do you sometimes think I am {}?"),
        "are_xyz":(     "Did you think they might not be {}?",
                    "Would you like it if they were not {}?",
                    "What if they were not {}?",
                    "Possibly they are {}."),
        "your_xyz":(    "Why are you concerned over my {}?",
                    "What about your own {}?",
                    "Are you worried about someone else's {}?",
                    "Really, my {}?"),
        "was_i_xyz":(   "What if you were {}?",
                    "Do you think you were {}?",
                    "Were you {}?"
                    "What would it mean if you were {}?",
                    "What does {} suggest to you?"),
        "i_was_xyz":(   "Were you really?",
                    "Why do you tell me you were {} now?",
                    "Perhaps I already know you were {}."),
        "was_you_xyz":( "Would you like to believe I was {}?",
                    "What suggests that I was {}?",
                    "What do you think?",
                    "Perhaps I was {}.",
                    "What if I had been {}?"),
        "i_desire_xyz":("What would it mean to you if you got {}?",
                    "Why do you want {}?",
                    "Suppose you got {} soon?",
                    "What if you never got {}?",
                    "What would getting {} mean to you?",
                    "What does wanting {} have to do with this discussion?"),
        "i_am_sad":("I am sorry to hear that you are {}.",
                    "Do you think that coming here will help you not to be {}?",
                    "I'm sure it's not pleasant to be {}.",
                    "Can you explain what made you {}?"),
        "i_am_happy":("How have I helped you to be {}?",
                    "Has your treatment made you {}?",
                    "What makes you {} just now?",
                    "Can you explan why you are suddenly {}?"),
        "i_belief_i_xyz":("Do you really think so?",
                    "But you are not sure you {}.",
                    "Do you really doubt you {}?"),
        "i_am_xyz":(    "Is it because you are {} that you came to me?",
                    "How long have you been {}?",
                    "Do you believe it is normal to be {}?",
                    "Do you enjoy being {}?"),
        "i_cant_xyz":(  "Why do you think that you can't {}?",
                    "Have you tried?",
                    "Perhaps you could {} now.",
                    "Do you really want to be able to {}?"),
        "i_dont_xyz":(  "Don't you really {}?",
                    "Why don't you {}?",
                    "Do you wish to be able to {}?",
                    "Does that trouble you?"),
        "do_i_feel_xyz":("Tell me more about such feelings.",
                    "Do you often feel {}?",
                    "Do you enjoy feeling {}?",
                    "Of what does feeling {} remind you?"),
        "i_xyz_you":(   "Perhaps in your fantasies we {} each other.",
                    "Do you wish to {} me?",
                    "You seem to need to {} me.",
                    "Do you {} anyone else?"),
        "i_xyz":(       "You say {}?",
                    "Can you elaborate on that?",
                    "Do you say {} for some special reason?",
                    "That's quite interesting."),
        "you_are_xyz":( "What makes you think I am {}?",
                    "Does it please you to believe I am {}?",
                    "Do you sometimes wish you were {}?",
                    "Perhaps you would like to be {}."),
        "you_xyz_me":(  "Why do you think I {} you?",
                    "You like to think I {} you -- don't you?",
                    "What makes you think I {} you?",
                    "Really, I {} you?",
                    "Do you wish to believe I {} you?",
                    "Suppose I did {} you -- what would that mean?",
                    "Does someone else believe I {} you?"),
        "you_xyz":(     "We were discussing you -- not me.",
                    "Oh, I {}?",
                    "You're not really talking about me -- are you?",
                    "What are your feelings now?"),
        "yes":(     "You seem to be quite positive.",
                    "You are sure.",
                    "I see.",
                    "I understand."),
        "no":(      "Are you saying no just to be negative?",
                    "You are being a bit negative.",
                    "Why not?",
                    "Why 'no'?"),
        "$my_xyz":(      "Lets discuss further why your {}.",
                    "Earlier you said your {}.",
                    "But your {}.",
                    "Does that have anything to do with the fact that your {}?"),
        "my_family_xyz":("Tell me more about your family.",
                    "Who else in your family {}?",
                    "Your {}?",
                    "What else comes to mind when you think of your {}?"),
        "my_xyz":(      "Your {}?",
                    "Why do you say your {}?",
                    "Does that suggest anything else which belongs to you?",   
                    "Is it important that your {}?"),
        "can_you_xyz":( "You believe I can {} don't you?",
                    "You want me to be able to {}.",
                    "Perhaps you would like to be able to {} yourself."),
        "can_i_xyz":(   "Whether or not you can {} depends on you more than me.",
                    "Do you want to be able to {}?",
                    "Perhaps you don't want to {}."),
        "what":(    "Why do you ask?",
                    "Does that question interest you?",
                    "What is it you really wanted to know?",
                    "Are such questions much on your mind?",
                    "What answer would please you most?",
                    "What do you think?",
                    "What comes to mind when you ask that?",
                    "Have you asked such questions before?",
                    "Have you asked anyone else?"),
        "because":( "Is that the real reason?",
                    "Don't any other reasons come to mind?",
                    "Does that reason seem to explain anything else?",
                    "What other reasons might there be?"),
        "why_dont_you_xyz":("Do you believe I don't {}?",
                    "Perhaps I will {} in good time.",
                    "Should you {} yourself?",
                    "You want me to {}?"),
        "why_cant_i_xyz":("Do you think you should be able to {}?",
                    "Do you want to be able to {}?",
                    "Do you believe this will help you to {}?",
                    "Have you any idea why you can't {}?"),
        "everyone":("Realy, {}?",
                    "Surely not {}.",
                    "Can you think of anyone in particular?",
                    "Who, for example?",
                    "Are you thinking of a very special person?",
                    "Who, may I ask?",
                    "Someone special perhaps?",
                    "You have a particular person in mind, don't you?",
                    "Who do you think you're talking about?"),
        "always":(  "Can you think of a specific example?",
                    "When?",
                    "What incident are you thinking of?",
                    "Really, always?"),
        "alike":(   "In what way?",
                    "What resemblence do you see?",
                    "What does that similarity suggest to you?",
                    "What other connections do you see?",
                    "What do you suppose that resemblence means?",
                    "What is the connection, do you suppose?",
                    "Could here really be some connection?",
                    "How?")
    }

    def all_keywords_objects(self,sentence):
        labels_objects = []
        patterns = {
            r"(bye|goodbye|quit) ":"bye",
            r"(sorry|apologise) ":"sorry",
            r"i remember (.*)":"i_remember_xyz",
            r"do you remember (.*)":"do_you_remember_xyz",
            r"if (.*)":"if_xyz",
            r"i (dreamed|dreamt) (.*)":"i_dreamed_xyz",
            r"(dream|dreams|dreamed|dreamt) ":"dream",
            r"(perhaps|maybe) ":"perhaps",
            r"name ":"name",
            r"(hello|hi|hiya) ":"hello",
            r"computer|computers|machine|machines|robot|robots":"computer",
            r"am i (.*)":"am_i_xyz",
            r"am ":"am",
            r"are you (.*)":"are_you_xyz",
            r"are (.*)":"are_xyz",
            r"your (.*)":"your_xyz",
            r"was i (.*)":"was_i_xyz",
            r"i was (.*)":"i_was_xyz",
            r"(was|were) you (.*)":"was_you_xyz",
            r"i .*(desire|want|need) (.*)":"i_desire_xyz",
            r"(im|i am) .*(sad|unhappy|sick)":"i_am_sad",
            r"(im|i am) .*(happy|elated|glad|better)":"i_am_happy",
            r"i .*(belief|believe|wish|think) .*(i|im) (.*)":"i_belief_i_xyz",
            r"i .*(belief|believe|wish|think) .*you (.*)":"i_belief_you_xyz",
            r"(im|i am) (.*)":"i_am_xyz",
            r"i .*(cant|cannot|can not) (.*)":"i_cant_xyz",
            r"i (dont|do not) (.*)":"i_dont_xyz",
            r"do i feel (.*)":"do_i_feel_xyz",
            r"i (.*) you":"i_xyz_you",
            r"i (.*)":"i_xyz",
            r"(youre|you are) (.*)":"you_are_xyz",
            r"you (.*) me":"you_xyz_me",
            r"you (.*)":"you_xyz",
            r"(yes|certainly) ":"yes",
            r"no ":"no",
            r"my (family|mother|mum|mummy|father|dad|daddy|sister|brother|wife|child|chilren) (.*)":"my_family_xyz",
            r"my (.*)":"my_xyz",
            r"can you (.*)":"can_you_xyz",
            r"can i (.*)":"can_i_xyz",
            r"(what|how|when|why) ":"what",
            r"because":"because",
            r"why dont you (.*)":"why_dont_you_xyz",
            r"why cant i (.*)":"why_cant_i_xyz",
            r"(everyone|everybody|noone|nobody) ":"everyone",
            r"always ":"always",
            r"(same|alike) ":"alike",
            r"you remind me of":"alike",
            r"(be|am|is|are|was|were) .*like":"alike",
        }
        for pattern,label in patterns.items():
            objs = re.search(pattern,sentence)
            if objs is not None:
                if label == 'my_xyz':
                    self.remember_it('$my_xyz',objs.group(1))
                labels_objects.append((label, objs.groups()))
        return labels_objects

    def best_keyword_object(self,sent_objs):
        kw_weights = {
            "bye":1,
            "sorry":1,
            "i_remember_xyz":5,
            "do_you_remember_xyz":5,
            "if_xyz":3,
            "i_dreamed_xyz":4,
            "dream":3,
            "perhaps":1,
            "name":15,
            "hello":1,
            "computer":50,
            "am_i_xyz":2,
            "am":1,
            "are_you_xyz":2,
            "are_xyz":1,
            "your_xyz":1,
            "was_i_xyz":2,
            "i_was_xyz":2,
            "was_you_xyz":2,
            "i_desire_xyz":2,
            "i_am_sad":3,
            "i_am_happy":3,
            "i_belief_i_xyz":2,
            "i_am_xyz":2,
            "i_cant_xyz":2,
            "i_dont_xyz":2,
            "do_i_feel_xyz":2,
            "i_xyz_you":2,
            "i_xyz":1,
            "you_are_xyz":2,
            "you_xyz_me":2,
            "you_xyz":1,
            "yes":1,
            "no":1,
            "$my_xyz":1,
            "my_family_xyz":2,
            "my_xyz":1,
            "can_you_xyz":2,
            "can_i_xyz":2,
            "what":1,
            "because":1,
            "why_dont_you_xyz":1,
            "why_cant_i_xyz":1,
            "everyone":2,
            "always":1,
            "alike":10
        }
        ranks_kws = [(kw_weights[keyword_objs[0]],keyword_objs) for keyword_objs in sent_objs if keyword_objs[0] in kw_weights]
        if len(ranks_kws) == 0:
            self.history.append('none')
        else:
            _,kw_obj = sorted(ranks_kws,reverse=True)[0]
            kw,obj = kw_obj
            self.history.append(kw)
            
            if len(obj) > 0:
                return obj[-1]

    def converse(self,utterance):
        return self.reply(self.best_keyword_object(self.all_keywords_objects(utterance.lower() + ' ')))

    def option(self,keyword):
        return (sum([1 for kw in self.history if kw == keyword]) % len(self.replies[keyword])) - 1

    def speak(self,keyword,obj = ''):
        return self.replies[keyword][self.option(keyword)].format(obj)

    def reply(self,obj=None):
        kw = self.history[-1]
        if kw == "none" and len(self.backup) > 0:
            r = self.backup[-1]
            self.backup.pop()
            return r
        return self.speak(kw,obj)

    def remember_it(self,label,obj):
        self.history.append(label)
        self.backup.append(self.replies[label][self.option(label)].format(obj))


e = Eliza()
while True:
    print('bot:', e.converse(input('user: ')))